default_context:
  project_name: 'My Dashboard project'
  project_slug: 'My-Dashboard'
  domain_main: 'My-Dashboard.com'
  domain_staging: 'stag.My-Dashboard.com'
  docker_swarm_stack_name_main: 'dashboard'
  docker_swarm_stack_name_staging: 'dashboard'
  secret_key: 'changethis'
  first_superuser: 'admin@My-Dashboard.com'
  first_superuser_password: 'changethis'
  backend_cors_origins: 'http://localhost, http://localhost:4200, http://localhost:3000, http://localhost:8080, https://localhost, https://localhost:4200, https://localhost:3000, https://localhost:8080, http://dev.My-Dashboard.com, https://stag.My-Dashboard.com, https://My-Dashboard.com, http://local.dockertoolbox.tiangolo.com, http://localhost.tiangolo.com'
  postgres_password: 'changethis'
  pgadmin_default_user: 'admin@My-Dashboard.com'
  pgadmin_default_user_password: 'changethis'
  traefik_constraint_tag: 'My-Dashboard.com'
  traefik_constraint_tag_staging: 'stag.My-Dashboard.com'
  traefik_public_network: 'traefik-public'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:changethis'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render:
    - frontend/src/**/*.html
    - frontend/src/**/*.vue
    - frontend/node_modules/*
  _template: ./
